# fly.toml app configuration file generated for godly-open-world on 2025-04-13T15:32:30+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'godly-open-world'
primary_region = 'sin'

[build]
  builder = "paketobuildpacks/builder:full"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = '8080'

[processes]
  app = 'node server.js'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
dockerfile = "Dockerfile"
